---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-server
  namespace: production
  labels:
    app: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stremio
  template:
    metadata:
      labels:
        app: stremio
    spec:
      containers:
        - name: stremio
          image: stremio/server:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: stremio-data
              mountPath: /root/.stremio-server
      volumes:
        - name: stremio-data
          persistentVolumeClaim:
            claimName: stremio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: stremio-service
  namespace: production
spec:
  selector:
    app: stremio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stremio-ingress
  namespace: production
spec:
  ingressClassName: nginx
  rules:
    - host: stremio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stremio-service
                port:
                  number: 80
