---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-server
  namespace: production
  labels:
    app: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stremio
  template:
    metadata:
      labels:
        app: stremio
    spec:
      containers:
        - name: stremio
          image: stremio/server:latest
          ports:
            - containerPort: 80
          # Added volumeMount for persistent storage
          volumeMounts:
            - name: stremio-data
              mountPath: /root/.stremio-server
      # Added volumes entry referencing the PVC
      volumes:
        - name: stremio-data
          persistentVolumeClaim:
            claimName: stremio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: stremio-service
  namespace: production
spec:
  selector:
    app: stremio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: stremio-pvc
#   namespace: production
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
