apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m0s
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.30.0"
  values:
    server:
      dataStorage:
        enabled: false
      standalone:
        enabled: false
      ha:
        enabled: true
        replicas: 1 # Reduce to 1 replica for testing
      service:
        type: ClusterIP
      configInline: |
        ui = true
        storage "file" {
          path = "/vault/data"
        }
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        service_registration "kubernetes" {}
    ui:
      enabled: true
    injector:
      enabled: true
