apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m0s
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.30.1"
  values:
    server:
      standalone:
        enabled: true
      service:
        type: ClusterIP
    ui:
      enabled: true
    injector:
      enabled: false
