apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unseal-reader
  namespace: vault
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["vault-unseal-keys"]
  verbs: ["get"]