---
# Vault Custom Resource managed by Bank-Vaults Operator
# Bank-Vaults Vault CR - manages Vault deployment, unsealing, and configuration
#
# NOTE: The Bank-Vaults operator automatically creates a 'vault-tls' Secret in the
# vault namespace containing the CA certificate used by ClusterSecretStore.
# This secret is created implicitly - see spec.config.listener.tls_cert_file/key_file.

apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  size: 1
  storeRootToken: false
  image: hashicorp/vault:1.15.2

  # Use dedicated service account with RBAC for unseal keys
  serviceAccount: vault

  # Kubernetes Secrets-based unsealing (protected by Phase 1 etcd encryption)
  unsealConfig:
    kubernetes:
      secretNamespace: vault
      secretName: vault-unseal-keys
    options:
      preFlightChecks: true
      secretShares: 5
      secretThreshold: 3

  # S3 storage credentials from Secret (created by bootstrap script)
  # Use vaultEnvsConfig to set AWS credentials as environment variables in the vault container
  vaultEnvsConfig:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: vault-storage-credentials
          key: ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: vault-storage-credentials
          key: SECRET_ACCESS_KEY

  # Vault server configuration
  config:
    api_addr: https://vault.vault.svc.cluster.local:8200
    cluster_addr: https://vault.vault.svc.cluster.local:8201

    listener:
      - tcp:
          address: "0.0.0.0:8200"
          tls_cert_file: /vault/tls/server.crt
          tls_key_file: /vault/tls/server.key

    storage:
      s3:
        endpoint: http://bootstrap-minio.bootstrap.svc.cluster.local:9000
        bucket: vault-storage
        region: us-east-1  # MinIO requires region
        disable_ssl: "true"
        s3_force_path_style: "true"  # Required for MinIO
        # Credentials from vault-storage-credentials Secret via credentialsConfig

    ui: true

    audit:
      - type: file
        description: File audit device for Vault operations
        options:
          file_path: /vault/audit/vault-audit.log
          mode: "0640"
          # Vault native log rotation settings
          rotation_max_files: 10
          rotation_max_bytes: 104857600  # 100MB per file
          rotation_duration: 24h

  # Automatic Vault configuration after initialization
  externalConfig:
    # Enable Kubernetes auth backend
    auth:
      - type: kubernetes
        path: kubernetes
        config:
          kubernetes_host: https://kubernetes.default.svc
        roles:
          - name: external-secrets
            bound_service_account_names:
              - external-secrets
            bound_service_account_namespaces:
              - external-secrets-system
            policies:
              - external-secrets
            ttl: 1h

    # Policies for External Secrets
    policies:
      - name: external-secrets
        rules: |
          path "secret/data/*" {
            capabilities = ["read", "list"]
          }
          path "secret/metadata/*" {
            capabilities = ["read", "list"]
          }

    # Enable KV v2 secrets engine
    secrets:
      - type: kv
        path: secret
        description: KV v2 secrets engine
        options:
          version: "2"

  # Resource allocation
  resources:
    vault:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Service configuration
  serviceType: ClusterIP

  # Monitoring (enable in Phase 3)
  serviceMonitorEnabled: false

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  # Volume for audit logs
  volumeClaimTemplates:
    - metadata:
        name: vault-audit
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
