---
# Flux Kustomization for Flux secrets managed by External Secrets
# These ExternalSecrets replace bootstrap-created secrets with Vault-managed ones
#
# Note: ExternalSecrets will fail until secrets are stored in Vault.
# This is expected - bootstrap secrets work until admin stores tokens in Vault.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/infrastructure/flux-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false  # Don't wait - ExternalSecret may fail until Vault has the secret
  timeout: 5m
  dependsOn:
    - name: external-secrets-config
