---
# Flux Kustomization for Vault
# Depends on vault-operator (needs CRD to be registered)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/infrastructure/vault
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
  dependsOn:
    - name: vault-operator
  healthChecks:
    - apiVersion: vault.banzaicloud.com/v1alpha1
      kind: Vault
      name: vault
      namespace: vault
