---
# Flux Kustomization for Bank-Vaults Operator
# First in dependency chain - no dependencies
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/infrastructure/vault-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vault-operator
      namespace: vault-operator
