creation_rules:
  - path_regex: .*\.sops\.(yaml|env|json)$
    encrypted_regex: ^(data|stringData)$
    age: age194eeq3s6z60qyzgjzpd48rsv2anlay7t69rdlluyvuy2qks7z4dq44wsh9
  - path_regex: .*\.txt$ # New: match your unseal_keys.txt/root_token.txt
    encrypted_regex: .* # encrypt the entire file
    age: age194eeq3s6z60qyzgjzpd48rsv2anlay7t69rdlluyvuy2qks7z4dq44wsh9
