apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-git-auth
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: flux-system
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .token }}"
        username: "git"
  data:
  - secretKey: token
    remoteRef:
      key: secret/github/auth
      property: token