apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    ingress:
    - hostname: "*.aac.gd"
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
    - hostname: "*.aacg.dev"
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
    - service: http_status:404
