apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/production/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: deployments
  targetNamespace: production
  dependsOn:
    - name: namespaces
    - name: pvc
  timeout: 2m
  wait: true
  force: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: stremio-server
      namespace: production
