---
# Flux Kustomization for External Secrets Operator
# Installs the operator and CRDs
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/external-secrets
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  dependsOn:
    - name: vault
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets-system
---
# Flux Kustomization for External Secrets Configuration
# ClusterSecretStore and ServiceAccount (depends on operator being ready)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/external-secrets-config
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  dependsOn:
    - name: external-secrets
  # Variable substitution from cluster-vars ConfigMap
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  healthChecks:
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      name: vault-backend
