apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: pvc
  namespace: flux-system
spec:
  # interval: 5m
  retryInterval: 1m
  timeout: 5m
  path: "./clusters/production/pvc"
  prune: true
  wait: true
  # sourceRef:
  #   kind: GitRepository
  #   name: flux-system
  # validation: client
  # kustomize:
  #   recurse: true  # Added to include subdirectories (e.g. apps, pvc)
