apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/tf-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-config
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tofu-controller
      namespace: flux-system
