apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.42.0.0/16  # Automatically allocate IPv4 addresses
  - fd42::/48       # Automatically allocate IPv6 addresses
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
  interfaces:
  - "^(eth|en|bond|wl).*"  # Adjust interface pattern as needed