---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    admissionWebhooks:
      enabled: true
---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-nginx-admission-ca
  namespace: ingress-nginx
  annotations:
    helm.toolkit.fluxcd.io/hook: post-sync
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: update-ca
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              CA_BUNDLE=$(kubectl get secret ingress-nginx-admission -n ingress-nginx -o jsonpath='{.data.ca}' | base64 --decode | base64)
              kubectl patch validatingwebhookconfiguration ingress-nginx-admission \
                --type=merge \
                -p "{\"webhooks\":[{\"name\":\"validate.nginx.ingress.kubernetes.io\",\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"}}]}"