apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m0s
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.30.0"
  values:
    server:
      # Add startup probe to give more time for initialization
      startupProbe:
        enabled: true
        failureThreshold: 60
        periodSeconds: 5
      readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
      livenessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true"
        initialDelaySeconds: 60
      extraEnvironmentVars:
        VAULT_LOG_LEVEL: debug
      dataStorage:
        enabled: true
        size: "10Gi"
        storageClass: "local-path"
        accessMode: "ReadWriteOnce"
      service:
        type: ClusterIP
      standalone:
        enabled: false # Explicitly disable standalone mode
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true # Important for HA setup
          config: |
            ui = true

            storage "raft" {
              path = "/vault/data"
              node_id = "${POD_NAME}"
              retry_join {
                leader_api_addr = "http://vault-0.vault-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-1.vault-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-2.vault-internal:8200"
              }
            }

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }

            service_registration "kubernetes" {}
      affinity: "" # Remove default anti-affinity
    ui:
      enabled: true
    injector:
      enabled: true
