---
# Vault Custom Resource managed by Bank-Vaults Operator
# Bank-Vaults Vault CR - manages Vault deployment, unsealing, and configuration
#
# TLS CERTIFICATE MANAGEMENT
# ==========================
# The Bank-Vaults operator automatically manages TLS certificates:
#
# 1. AUTOMATIC CREATION:
#    - Operator creates 'vault-tls' Secret in vault namespace on first deployment
#    - Contains: ca.crt, server.crt, server.key
#    - Used by ClusterSecretStore for secure Vault communication
#
# 2. CERTIFICATE RENEWAL:
#    - Bank-Vaults operator monitors cert expiry and auto-renews before expiration
#    - Default validity: 1 year, renewal threshold: 30 days before expiry
#    - Vault pods are automatically restarted when certs are renewed
#    - No manual intervention required under normal operation
#
# 3. MANUAL RENEWAL (if needed):
#    - Delete the vault-tls secret: kubectl delete secret vault-tls -n vault
#    - Restart the vault-operator: kubectl rollout restart deployment -n vault-operator vault-operator
#    - Operator will regenerate certificates automatically
#
# 4. MONITORING:
#    - Check cert expiry: kubectl get secret vault-tls -n vault -o jsonpath='{.data.server\.crt}' | base64 -d | openssl x509 -noout -enddate
#    - Vault operator logs show renewal events: kubectl logs -n vault-operator -l app.kubernetes.io/name=vault-operator

apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
  annotations:
    # Prevent Flux from deleting this resource if file is accidentally removed from git
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  size: 1
  image: hashicorp/vault:1.15.2

  # Use dedicated service account with RBAC for unseal keys
  serviceAccount: vault

  # Kubernetes Secrets-based unsealing (protected by Phase 1 etcd encryption)
  unsealConfig:
    kubernetes:
      secretNamespace: vault
      secretName: vault-unseal-keys
    options:
      preFlightChecks: true
      secretShares: 5
      secretThreshold: 3
      storeRootToken: false

  # S3 storage credentials from Secret (created by bootstrap script)
  # Use vaultEnvsConfig to set AWS credentials as environment variables in the vault container
  vaultEnvsConfig:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: vault-storage-credentials
          key: ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: vault-storage-credentials
          key: SECRET_ACCESS_KEY

  # Vault server configuration
  # NOTE: Variables substituted by Flux from cluster-vars ConfigMap
  config:
    api_addr: ${VAULT_ADDR}
    cluster_addr: ${VAULT_CLUSTER_ADDR}

    listener:
      - tcp:
          address: "0.0.0.0:8200"
          tls_cert_file: /vault/tls/server.crt
          tls_key_file: /vault/tls/server.key

    storage:
      s3:
        endpoint: ${MINIO_ENDPOINT}
        bucket: vault-storage
        region: local  # MinIO accepts any string; "local" is clearer than fake AWS region
        disable_ssl: "true"
        s3_force_path_style: "true"  # Required for MinIO
        # Credentials from vault-storage-credentials Secret via credentialsConfig

    ui: true

    audit:
      - type: file
        description: File audit device for Vault operations
        options:
          file_path: /vault/audit/vault-audit.log
          mode: "0640"
          # Vault native log rotation settings
          rotation_max_files: 10
          rotation_max_bytes: 104857600  # 100MB per file
          rotation_duration: 24h

  # Automatic Vault configuration after initialization
  externalConfig:
    # Enable Kubernetes auth backend
    auth:
      - type: kubernetes
        path: kubernetes
        config:
          kubernetes_host: https://kubernetes.default.svc
        roles:
          - name: external-secrets
            bound_service_account_names:
              - external-secrets
            bound_service_account_namespaces:
              - external-secrets-system
            policies:
              - external-secrets
            ttl: 1h
          - name: secret-writer
            bound_service_account_names:
              - vault-secret-writer
            bound_service_account_namespaces:
              - vault-jobs
            policies:
              - secret-writer
            ttl: 1h
          - name: tf-controller
            bound_service_account_names:
              - tf-controller-vault
            bound_service_account_namespaces:
              - flux-system
            policies:
              - tf-controller
            ttl: 1h

    # Policies for External Secrets
    policies:
      - name: external-secrets
        rules: |
          path "secret/data/*" {
            capabilities = ["read", "list"]
          }
          path "secret/metadata/*" {
            capabilities = ["read", "list"]
          }
      - name: secret-writer
        rules: |
          path "secret/data/bootstrap/*" {
            capabilities = ["create", "update", "patch"]
          }
          path "secret/data/infra/*" {
            capabilities = ["create", "update", "patch"]
          }
          path "secret/data/flux/*" {
            capabilities = ["create", "update", "patch"]
          }
      - name: tf-controller
        rules: |
          # Token creation required by Vault Terraform provider
          path "auth/token/create" {
            capabilities = ["create", "update"]
          }
          path "secret/data/bootstrap/inputs" {
            capabilities = ["read"]
          }
          path "secret/data/infra/*" {
            capabilities = ["create", "update", "read", "delete"]
          }
          path "secret/metadata/infra/*" {
            capabilities = ["read", "list"]
          }
          path "secret/data/apps/*" {
            capabilities = ["create", "update", "read", "delete"]
          }
          path "secret/metadata/apps/*" {
            capabilities = ["read", "list"]
          }

    # Enable KV v2 secrets engine
    secrets:
      - type: kv
        path: secret
        description: KV v2 secrets engine
        options:
          version: "2"

  # Resource allocation
  resources:
    vault:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Service configuration
  serviceType: ClusterIP

  # Monitoring (enable when monitoring stack is deployed)
  serviceMonitorEnabled: false

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  # Volume for audit logs
  volumeClaimTemplates:
    - metadata:
        name: vault-audit
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
