apiVersion: v1
kind: Service
metadata:
  name: stremio-service
  namespace: production
spec:
  selector:
    app: stremio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11470
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: stremio-nodeport
  namespace: production
spec:
  type: NodePort
  selector:
    app: stremio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11470
      nodePort: 30080
