---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: vault-operator
      version: "1.22.2"
      sourceRef:
        kind: HelmRepository
        name: bank-vaults
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: "v1.22.2"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    # ARM64 compatibility
    nodeSelector:
      kubernetes.io/arch: arm64
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
