apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-server
  namespace: production
  labels:
    app: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stremio
  template:
    metadata:
      labels:
        app: stremio
    spec:
      containers:
        - name: stremio
          image: stremio/server:latest
          ports:
            - containerPort: 11470
              name: http
              protocol: TCP
            - containerPort: 12470
              name: https
              protocol: TCP
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          volumeMounts:
            - name: stremio-data
              mountPath: /root/.stremio-server
      volumes:
        - name: stremio-data
          persistentVolumeClaim:
            claimName: stremio-pvc
