apiVersion: v1
kind: Service
metadata:
  name: stremio-service
  namespace: production
spec:
  selector:
    app: stremio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11470
      name: http
    - protocol: TCP
      port: 443
      targetPort: 12470
      name: https
