---
# Service account for Vault authentication
# NOTE: Namespace external-secrets-system must exist before this is applied.
# Created by external-secrets/namespace.yaml, ensured via Flux dependsOn in external-secrets.yaml.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets-system
  annotations:
    vault.hashicorp.com/auth-path: auth/kubernetes
    vault.hashicorp.com/role: external-secrets
---
# ClusterRole for External Secrets to read secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-vault
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets-system
