apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: vault-secrets
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 5m
  path: ./modules/vault-secrets
  sourceRef:
    kind: GitRepository
    name: infra
  approvePlan: auto
  serviceAccountName: tf-controller-vault

  # MinIO S3 backend
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket                      = "terraform-state"
        key                         = "vault-secrets/terraform.tfstate"
        endpoint                    = "http://minio.storage.svc:9000"
        region                      = "us-east-1"
        skip_credentials_validation = true
        skip_metadata_api_check     = true
        skip_region_validation      = true
        force_path_style            = true
      }

  # MinIO credentials for S3 backend and Vault address
  # Uses tf-minio-credentials (tf-user with terraform-state bucket access only)
  runnerPodTemplate:
    spec:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tf-minio-credentials
              key: ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tf-minio-credentials
              key: SECRET_ACCESS_KEY
        # Terraform reads TF_VAR_* env vars automatically
        - name: TF_VAR_vault_addr
          valueFrom:
            configMapKeyRef:
              name: cluster-vars
              key: VAULT_ADDR
