apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "16.0.8"
  values:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: local-path
