apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tofu-controller
      version: "0.16.x"
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
