apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-minio-credentials
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: tf-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: secret/data/infra/minio/tf-user
        property: access_key
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: secret/data/infra/minio/tf-user
        property: secret_key
